general.import = ["~/.config/alacritty/colors/everforest-med.toml"]

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
blink_timeout = 30
unfocused_hollow = true
thickness = 0.1

[env]
TERM = "xterm-256color"

[font]
size = 9.5

[font.bold]
family = "JetBrainsMono NFP"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFP"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFP"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFP"
style = "Regular"

[window.dimensions]
columns = 86
lines = 24

[window.padding]
x = 5
y = 5

[window]
opacity = 1
dynamic_title = true
